#!/bin/sh

#####
#   clean up
#####
rm -f magtable.txt

#####
#    the original 2014.csv has Columns separated by comma
#    Here get rid of the first two lines with names,
#    remove the commas, and then print the NEW columns 3 4 and 12s
#    which are the latitude longitude and preferred magnitude
#####



for YEAR in 2001 2004 2009 2012 2014 2016 2018
do
        echo $YEAR
        cat ${YEAR}.csv |tail -n +2|  awk -F, '{print $3,$4,$12}' > latlonmag${YEAR}.txt
    #####
        #     here use awk to find the subset of events within a latitude longitude box
        #     then print the magnitude
        #####
        cat latlonmag${YEAR}.txt | awk '{if($1>=35.5 && $1<=36.5 && $2>=-97.5 && $2<=-96.5) printf "%.1f\n",$3}' > maglist${YEAR}.txt

        #####
#    get the largest and smallest
        #####
        LARGEST=`cat maglist${YEAR}.txt | sort -n | tail -1 `
        SMALLEST=`cat maglist${YEAR}.txt | sort -nr | tail -1 `
        NUMBER=`wc -l maglist${YEAR}.txt`

        echo Largest $LARGEST smallest $SMALLEST  in ${YEAR} Number earthquakes = ${NUMBER} >> magtable.txt
done


